local DMW = DMW
DMW.Rotations.SHAMAN = {}
local Shaman = DMW.Rotations.SHAMAN
local UI = DMW.UI

function Shaman.Settings()
    UI.AddHeader("Totems", "use totems", true)
	UI.AddToggle("Strength Of Earth Totem", nil, false)
	UI.AddToggle("Windfury Totem", nil, false)
	UI.AddToggle("Grace Of Air Totem", nil, false)
	UI.AddToggle("Searing Totem", nil, false)   
	UI.AddRange("Searing Totem Mana", nil, 0, 100, 1, 79)	 
	UI.AddToggle("Magma Totem","use on 2+ mobs", nil, true)
	UI.AddRange("Magma Totem Mana", nil, 0, 100, 1, 79)
	UI.AddToggle("Fire Nova Totem","use on 2+ mobs", nil, true)
	UI.AddRange("Fire Nova Totem Mana", nil, 0, 100, 1, 79)
	UI.AddHeader("Utility")
	UI.AddToggle("Auto Target", "Auto target units when in combat and target dead/missing", false)
    UI.AddToggle("Auto Target Quest Units", nil, false)
	UI.AddToggle("Orc Racial", nil, true)	
	UI.AddToggle("Lightning Shield", nil, true)	
    UI.AddToggle("Weapon Enchant", nil, true)
    UI.AddToggle("Earth Shock Interrupt", "Rank 1 earth shock to interrupt", nil, true)
	UI.AddToggle("Frost Shock Runner", "Use on Fleeing Humanoids", nil, true)
	UI.AddHeader("Defensives")
	UI.AddToggle("Stoneskin Totem", nil, false)
	UI.AddToggle("Ston Claw Totem","taunt when 2+ mobs", nil, true)
	UI.AddHeader("Self healing")	
	UI.AddToggle("In Combat Heal", nil, false)
	UI.AddRange("Lesser Heal HP", nil, 0, 100, 1, 29)	
	UI.AddToggle("OOC Healing", nil, true)
	UI.AddRange("OOC Healing Percent HP", nil, 0, 100, 1, 50)
	UI.AddRange("OOC Healing Percent Mana", nil, 0, 100, 1, 50)	
	UI.AddHeader("Opener")
	UI.AddToggle("Lightning Bolt","Rank 1 to pull", nil, true)
	UI.AddHeader("DPS")
	UI.AddToggle("Earth Shock", nil, true)
	UI.AddRange("Earth Shock Mana", nil, 0, 100, 1, 50)	
	UI.AddToggle("Flame Shock", nil, false)
	UI.AddRange("Flame Shock Mana", nil, 0, 100, 1, 50)	
	UI.AddToggle("Stormstrike",nil,true)
end